### ISSUE TITLE
...../lib/jsduck/class.rb:50:in `merge!': can't convert nil into Hash (TypeError)

### ISSUE THREAD

**Issue by garytaylor** [senchalabs/jsduck#575]
Since upgrading my Ext 5.0.0  project to Ext 5.0.1, I started having this error when building the docs.
I am using 'grunt-jsduck' to run jsduck, but the same happens when run from the command line directly.
The problem occurs when I document the ext/src directory as well as ext/packages/*/src - as soon as it comes across the packages/sencha-charts/src/chart/CartestianChart .js class, that includes a line saying 'alternativeClassName: 'Ext.chart.Chart' the problem shows.  If I temporarily remove this line, it works fine.

Here is the full stack trace from ruby

```
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:50:in `merge!': can't convert nil into Hash (TypeError)
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:50:in `block (2 levels) in internal_doc='
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:49:in `zip'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:49:in `block in internal_doc='
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:47:in `merge!'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/class.rb:47:in `internal_doc='
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/format/batch.rb:36:in `block in format_all!'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/format/batch.rb:35:in `each'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/format/batch.rb:35:in `format_all!'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/web/writer.rb:80:in `format_classes'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/web/writer.rb:39:in `write'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/app.rb:58:in `generate_web_page'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/lib/jsduck/app.rb:28:in `run'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/jsduck-5.3.4/bin/jsduck:25:in `<top (required)>'
        from C:/opscode/chef/embedded/bin/jsduck:23:in `load'
        from C:/opscode/chef/embedded/bin/jsduck:23:in `<main>'
```

**Comment by blendsdk** [comment]
I have the same problem. Is there any fix for this?
