### ISSUE TITLE
unicode identifier Error while parsing file..: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by and-y** [senchalabs/jsduck#620]
jsduck crashes with the error `Error while parsing {file}: undefined method `name' for nil:NilClass` when an identifier contains an unicode character e.g. ß or ಠ.

    Ext.define('Test.util.Date', {
         teßt: function() { // will crash because of ß
         }
    });

But valid javascript identifier can contain it see http://stackoverflow.com/a/9337047/1732133

> An identifier must start with $, _, or any character in the Unicode categories “Uppercase letter (Lu)”, “Lowercase letter (Ll)”, “Titlecase letter (Lt)”, “Modifier letter (Lm)”, “Other letter (Lo)”, or “Letter number (Nl)”.
>
>The rest of the string can contain the same characters, plus any U+200C zero width non-joiner characters, U+200D zero width joiner characters, and characters in the Unicode categories “Non-spacing mark (Mn)”, “Spacing combining mark (Mc)”, “Decimal digit number (Nd)”, or “Connector punctuation (Pc)”.

**Comment by nene** [comment]
Thanks. That's a known problem in RKelly parser: https://github.com/tenderlove/rkelly/issues/35

But seems that somebody has written a patch for it: https://github.com/tokenrove/rkelly-remix/commit/0d023dac3aa656d1565e4b62590e8e4b3aeb98ec

Should take a look at that...

**Comment by nene** [comment]
There are also problems in JSDuck itself regarding special characters in identifiers: https://github.com/senchalabs/jsduck/issues/497

So the issue is more involved...

**Comment by nuri-engin** [comment]
Dear @nene probably I've faced with same problem during creating docs. I've used this command;
`jsduck sencha-sdks/ext-6.5.2/build Dev/Project/subproject/myapp --output docs`

and it respons as this;
`Error: Error while parsing /Users/frontend/sencha-sdks/ext-6.5.2/build/classic/locale/locale-pl-debug.js: undefined method `name' for nil:NilClass

Here's a full backtrace:
/Users/frontend/.gem/ruby/2.0.0/gems/rkelly-remix-0.0.7/lib/rkelly/tokenizer.rb:199:in `raw_tokens'
/Users/frontend/.gem/ruby/2.0.0/gems/rkelly-remix-0.0.7/lib/rkelly/parser.rb:40:in `parse'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/js/parser.rb:22:in `parse'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/parser.rb:44:in `parse_js_or_css'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/parser.rb:30:in `parse'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/batch_parser.rb:25:in `block in parse'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:339:in `call'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:339:in `call_with_index'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:268:in `process_incoming_jobs'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:251:in `block in worker'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:244:in `fork'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:244:in `worker'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:232:in `block in create_workers'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:231:in `each'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:231:in `create_workers'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:195:in `work_in_processes'
/Users/frontend/.gem/ruby/2.0.0/gems/parallel-0.7.1/lib/parallel.rb:106:in `map'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/util/parallel.rb:28:in `map'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/batch_parser.rb:17:in `parse'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/app.rb:41:in `parse'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/lib/jsduck/app.rb:21:in `run'
/Users/frontend/.gem/ruby/2.0.0/gems/jsduck-5.3.4/bin/jsduck:25:in `<main>'`
