### ISSUE TITLE
Error thrown when running

### ISSUE THREAD

**Issue by lijinxieyang** [senchalabs/jsduck#671]
```
E:\study\jquery-plugins>jsduck
C:/Users/ZHOUYA~1/AppData/Local/Temp/ocr8C3D.tmp/lib/ruby/gems/1.9.1/gems/jsduck
-5.3.4/lib/jsduck/options.rb:871:in `parse_options': ambiguous option: -encoding
 (OptionParser::AmbiguousOption)
        from C:/Users/ZHOUYA~1/AppData/Local/Temp/ocr8C3D.tmp/lib/ruby/gems/1.9.
1/gems/jsduck-5.3.4/lib/jsduck/options.rb:879:in `auto_detect_config_file'
        from C:/Users/ZHOUYA~1/AppData/Local/Temp/ocr8C3D.tmp/lib/ruby/gems/1.9.
1/gems/jsduck-5.3.4/lib/jsduck/options.rb:172:in `parse!'
        from C:/Users/ZHOUYA~1/AppData/Local/Temp/ocr8C3D.tmp/lib/ruby/gems/1.9.
1/gems/jsduck-5.3.4/bin/jsduck:24:in `<main>'
```

**Comment by nene** [comment]
Looks like you're trying to use `--encoding` option, but you've written it with just one dash: `-encoding`.

**Comment by lijinxieyang** [comment]
The problem is solved.Thank you very much.
