### ISSUE TITLE
Why on code don't useing parse self-contained function

### ISSUE THREAD

**Issue by WuYuansen** [senchalabs/jsduck#679]
exception code:
```
Here's a full backtrace:
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/rkelly-remix-0.0.4/lib/rkelly/tokenizer.rb:158:in `raw_tokens'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/rkelly-remix-0.0.4/lib/rkelly/parser.rb:40:in `parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/js/parser.rb:22:in `parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/parser.rb:44:in `parse_js_or_css'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/parser.rb:30:in `parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/batch_parser.rb:25:in `block in parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/util/parallel.rb:26:in `map'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/util/parallel.rb:26:in `map'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/batch_parser.rb:17:in `parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/app.rb:41:in `parse'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/lib/jsduck/app.rb:21:in `run'
C:/Users/l/AppData/Local/Temp/ocr2F8E.tmp/lib/ruby/gems/1.9.1/gems/jsduck-5.3.2/bin/jsduck:25:in `<main>'
```

**Comment by nene** [comment]
Please post the code that JSDuck is parsing.
